// All copy, FR first then EN. Only facts from the audit of the old site; nothing invented.
// Typography: French uses non-breaking spaces ( ,  ) before : ; ? ! and in amounts.

export const PAGES = [
  { key: "home", fr: "", en: "en/" },
  { key: "paint", fr: "peinture-fer-forge-montreal/", en: "en/wrought-iron-painting-montreal/" },
  { key: "weld", fr: "restauration-soudure-fer-forge-montreal/", en: "en/wrought-iron-restoration-welding-montreal/" },
  { key: "work", fr: "realisations/", en: "en/projects/" },
  { key: "about", fr: "a-propos/", en: "en/about/" },
  { key: "areas", fr: "zones-desservies/", en: "en/service-area/" },
  { key: "faq", fr: "faq/", en: "en/faq/" },
  { key: "guides", fr: "guides/", en: "en/guides/" },
  { key: "g1", fr: "guides/repeindre-ou-restaurer-escaliers-copropriete/", en: "en/guides/repaint-or-restore-condo-stairs/" },
  { key: "g2", fr: "guides/preparer-projet-fer-forge-copropriete/", en: "en/guides/plan-wrought-iron-project-condo/" },
  { key: "contact", fr: "contact-devis/", en: "en/contact-quote/" },
  { key: "privacy", fr: "politique-de-confidentialite/", en: "en/privacy-policy/" },
];

export const UI = {
  fr: {
    skip: "Aller au contenu",
    nav: { home: "Accueil", services: "Services", paint: "Peinture de fer forgé", weld: "Restauration et soudure", work: "Réalisations", about: "À propos", areas: "Zones desservies", faq: "FAQ", guides: "Guides", contact: "Contact / Devis" },
    quote: "Soumission gratuite", quoteLong: "Obtenir une soumission gratuite", call: "Appeler", callNow: "Appeler le",
    menu: "Menu", close: "Fermer", langName: "English", langShort: "EN",
    footerLinks: "Liens utiles", footerContact: "Nous joindre", footerServices: "Services", footerLegal: "Légal",
    rights: "Tous droits réservés.", privacy: "Politique de confidentialité", cookies: "Gérer les témoins (cookies)",
    scroll: "Défiler", reviews: "avis Google", ratingLabel: "Note Google", seeReviews: "Lire les avis sur Google",
    cookieText: "Nous utilisons des témoins (cookies) de mesure d’audience uniquement avec votre accord. Aucun n’est déposé avant votre choix.",
    cookieAccept: "Accepter", cookieRefuse: "Refuser", cookieMore: "En savoir plus",
    breadcrumbHome: "Accueil",
    readGuide: "Lire le guide", allGuides: "Tous les guides",
    illustration: "Image illustrative", before: "Avant", after: "Après",
    sliderHint: "Glissez pour comparer",
    send: "Envoyer ma demande", sending: "Envoi…",
    sentTitle: "Merci, votre demande est envoyée.", sentText: "Nous vous répondons rapidement, en général dans la journée ouvrable.",
    fallbackTitle: "Presque terminé", fallbackText: "Votre application courriel va s’ouvrir avec votre demande. Pensez à y joindre vos photos.",
    errRequired: "Ce champ est obligatoire.", errEmail: "Entrez un courriel valide.", errPhone: "Entrez un numéro de téléphone valide.", errPostal: "Entrez un code postal valide.", errConsent: "Veuillez accepter pour continuer.", errFiles: "Maximum 5 photos de 8 Mo chacune.",
  },
  en: {
    skip: "Skip to content",
    nav: { home: "Home", services: "Services", paint: "Wrought iron painting", weld: "Restoration & welding", work: "Projects", about: "About", areas: "Service area", faq: "FAQ", guides: "Guides", contact: "Contact / Quote" },
    quote: "Free quote", quoteLong: "Get a free quote", call: "Call", callNow: "Call",
    menu: "Menu", close: "Close", langName: "Français", langShort: "FR",
    footerLinks: "Quick links", footerContact: "Contact us", footerServices: "Services", footerLegal: "Legal",
    rights: "All rights reserved.", privacy: "Privacy policy", cookies: "Manage cookies",
    scroll: "Scroll", reviews: "Google reviews", ratingLabel: "Google rating", seeReviews: "Read the reviews on Google",
    cookieText: "We only use audience-measurement cookies with your consent. None are set before you choose.",
    cookieAccept: "Accept", cookieRefuse: "Decline", cookieMore: "Learn more",
    breadcrumbHome: "Home",
    readGuide: "Read the guide", allGuides: "All guides",
    illustration: "Illustrative image", before: "Before", after: "After",
    sliderHint: "Drag to compare",
    send: "Send my request", sending: "Sending…",
    sentTitle: "Thank you, your request has been sent.", sentText: "We reply quickly, usually within one business day.",
    fallbackTitle: "Almost done", fallbackText: "Your email app will open with your request. Remember to attach your photos.",
    errRequired: "This field is required.", errEmail: "Enter a valid email.", errPhone: "Enter a valid phone number.", errPostal: "Enter a valid postal code.", errConsent: "Please accept to continue.", errFiles: "Up to 5 photos, 8 MB each.",
  },
};

// Structures worked on (painting page and home)
export const STRUCTURES = [
  { id: "balcon", fr: "Balcons en fer forgé", en: "Wrought-iron balconies" },
  { id: "service", fr: "Escaliers de service", en: "Service stairs" },
  { id: "colimacon", fr: "Escaliers en colimaçon", en: "Spiral staircases" },
  { id: "facade", fr: "Escaliers de façade", en: "Front-façade stairs" },
  { id: "garde", fr: "Garde-corps et clôtures", en: "Railings and fences" },
];

export const PROCESS = [
  { fr: ["Protection des lieux", "Nous protégeons les surfaces avoisinantes : briques, vitres, planchers, végétation. Le chantier reste propre du premier au dernier jour."], en: ["Protecting the site", "We protect everything around the work: brick, glass, floors, plants. The site stays clean from the first day to the last."] },
  { fr: ["Grattage et brossage", "L’écaillement et la peinture qui se détache sont retirés pour repartir sur une base saine."], en: ["Scraping and brushing", "Flaking and loose paint are removed so the new coating starts on a sound base."] },
  { fr: ["Meulage de la rouille", "La rouille est meulée et les surfaces nettoyées. C’est l’étape qui décide de la durée de vie du travail."], en: ["Rust grinding", "Rust is ground out and the surfaces cleaned. This is the step that decides how long the work lasts."] },
  { fr: ["Primer antirouille", "Un apprêt antirouille est appliqué sur le métal mis à nu pour bloquer la corrosion à la source."], en: ["Anti-rust primer", "An anti-rust primer goes onto the bare metal to stop corrosion at the source."] },
  { fr: ["Peinture industrielle", "Une peinture à métal industrielle, conçue pour résister aux intempéries, termine le travail avec une finition soignée."], en: ["Industrial paint", "An industrial metal paint, built to withstand the weather, completes the work with a clean finish."] },
];

export const WELD_STRUCTURES = [
  { fr: ["Consolidation de main courante", "Une main courante fragilisée est consolidée avant qu’elle ne devienne un risque."], en: ["Handrail consolidation", "A weakened handrail is reinforced before it becomes a risk."] },
  { fr: ["Renforcement de limons", "Les limons, qui portent les marches, sont renforcés là où le métal est aminci."], en: ["Stringer reinforcement", "Stringers, which carry the treads, are reinforced where the metal has thinned."] },
  { fr: ["Remplacement de triangles", "Les triangles d’appui trop dégradés sont remplacés par de nouvelles pièces soudées."], en: ["Bracket replacement", "Support brackets that are too far gone are replaced with new welded parts."] },
  { fr: ["Renforcement de base de garde-corps", "La base des poteaux, première zone touchée par la rouille, est renforcée."], en: ["Railing-base reinforcement", "The base of the posts, the first area hit by rust, is reinforced."] },
];

// Real client reviews from the old site (initials as published). TODO(owner): confirm each is a Google review and add dates.
export const REVIEWS = [
  { n: "N. Langevin", fr: "Communication rapide, travail bien fait et délais respectés. Rien à redire, tout s’est passé comme prévu. C’est rare de nos jours, donc ça mérite d’être mentionné.", en: "Quick communication, good work and deadlines met. Nothing to complain about, everything went as planned. That is rare these days, so it deserves a mention." },
  { n: "L. Beaulieu", fr: "Excellent service client et des résultats qui parlent par eux-mêmes. Je recommande !", en: "Excellent customer service and results that speak for themselves. I recommend them!" },
  { n: "M. Lacroix", fr: "Très satisfait du service. Travail bien fait et professionnel. Bonne communication et résultat à la hauteur de mes attentes. Je recommande.", en: "Very satisfied with the service. Well-done, professional work. Good communication and a result that met my expectations. I recommend them." },
  { n: "A. Turcotte", fr: "Un travail impeccable et très professionnel. Je recommande fortement.", en: "Impeccable, very professional work. I strongly recommend them." },
  { n: "M. Doucet", fr: "J’ai fait affaire avec cette entreprise pour deux projets dans les dernières années et je vais continuer de le faire. Service professionnel et résultat durable.", en: "I have used this company for two projects over the last few years and I will keep doing so. Professional service and a lasting result." },
  { n: "V. Germain", fr: "Excellent service et qualité A1. Sympathique et honnête ! Je recommande à 100 %.", en: "Excellent service and top quality. Friendly and honest! I recommend them 100%." },
  { n: "Z. Pontbriand", fr: "La qualité de la finition est excellente et on voit tout de suite leur expertise dans le domaine du fer forgé. Je recommande sans hésiter à quiconque cherche un service fiable à Montréal.", en: "The quality of the finish is excellent and their expertise in wrought iron is obvious right away. I recommend them without hesitation to anyone looking for a reliable service in Montréal." },
];

export const FAQ = [
  { q: { fr: "Quels types de structures en fer forgé traitez-vous ?", en: "What kinds of wrought-iron structures do you work on?" }, a: { fr: "Balcons, escaliers de service, escaliers en colimaçon, escaliers de façade, garde-corps, mains courantes et clôtures, à Montréal et aux environs.", en: "Balconies, service stairs, spiral staircases, front-façade stairs, railings, handrails and fences, in Montréal and the surrounding area." } },
  { q: { fr: "Faites-vous la soudure en plus de la peinture ?", en: "Do you do welding as well as painting?" }, a: { fr: "Oui. Nous remplaçons les sections trop dégradées, redressons les structures et renforçons les zones amincies, puis nous peignons l’ensemble. Vous n’avez qu’un seul interlocuteur du début à la fin.", en: "Yes. We replace sections that are too degraded, straighten structures and reinforce thinned areas, then paint the whole. You deal with a single contractor from start to finish." } },
  { q: { fr: "À qui s’adressent vos services ?", en: "Who are your services for?" }, a: { fr: "Principalement aux copropriétés, aux coopératives d’habitation et aux propriétaires d’immeubles pour des projets d’entretien moyens et gros.", en: "Mainly condo associations, housing co-ops and building owners, for medium and large maintenance projects." } },
  { q: { fr: "Y a-t-il un montant minimal par projet ?", en: "Is there a minimum project amount?" }, a: { fr: "Oui, nous avons présentement un montant minimal de 3 000 $ par projet. La soumission est gratuite.", en: "Yes, we currently have a minimum of $3,000 per project. The quote is free." } },
  { q: { fr: "Comment se déroule la peinture d’un garde-corps ou d’un escalier ?", en: "How is a railing or staircase painted?" }, a: { fr: "Protection des surfaces avoisinantes, grattage et brossage de l’écaillement, meulage de la rouille et nettoyage, application d’un primer antirouille, puis d’une peinture à métal industrielle.", en: "We protect the surrounding surfaces, scrape and brush the flaking, grind out rust and clean, then apply an anti-rust primer followed by an industrial metal paint." } },
  { q: { fr: "Pourquoi le fer forgé se détériore-t-il à Montréal ?", en: "Why does wrought iron deteriorate in Montréal?" }, a: { fr: "Le climat québécois expose le métal à l’humidité, au gel et au dégel et aux sels de déglaçage. La rouille s’installe là où la peinture est écaillée, puis amincit le métal.", en: "Québec’s climate exposes metal to moisture, freeze-thaw cycles and de-icing salt. Rust sets in wherever paint has flaked, then thins the metal." } },
  { q: { fr: "Comment obtenir une soumission ?", en: "How do I get a quote?" }, a: { fr: "Remplissez le formulaire de la page Contact avec quelques photos, ou appelez-nous. Plus vous décrivez la structure, plus la soumission est précise.", en: "Fill in the form on the Contact page with a few photos, or call us. The better you describe the structure, the more precise the quote." } },
  { q: { fr: "Quelle est la garantie sur vos travaux ?", en: "What warranty do you give on your work?" }, a: { fr: "Les conditions de garantie sont précisées dans chaque soumission. Demandez-les lors de votre demande.", en: "Warranty terms are stated in each quote. Ask for them when you request one." } },
];

export const GUIDES = {
  g1: {
    fr: { title: "Repeindre ou restaurer les escaliers de votre copropriété : comment décider", tt: "Repeindre ou restaurer escaliers de copropriété", desc: "Peinture seule ou soudure d’abord ? Les signes qui indiquent le bon traitement pour les escaliers et balcons en fer forgé d’une copropriété.", lead: "Pour un conseil d’administration, la bonne question n’est pas « combien ça coûte de repeindre ? » mais « dans quel état est le métal ? ». La réponse décide de tout le reste.", sections: [
      ["Quand la peinture suffit", ["Le métal est sain : pas de perforation, pas de section amincie, pas de jeu dans les assemblages.", "La peinture est écaillée, mais la rouille est de surface et peut être meulée.", "Dans ce cas, une préparation sérieuse, un primer antirouille et une peinture industrielle remettent la structure à neuf pour de longues années."]],
      ["Quand il faut souder d’abord", ["Des sections sont percées, très amincies ou déformées.", "Une main courante, un poteau ou un limon bouge.", "La rouille a attaqué la base des garde-corps ou les triangles d’appui.", "Peindre par-dessus ne règle rien : il faut d’abord remplacer ou renforcer, puis peindre."]],
      ["Pourquoi tout confier au même entrepreneur", ["Quand la soudure et la peinture sont faites par la même équipe, la préparation est continue, les responsabilités sont claires et il n’y a pas de coordination entre deux sous-traitants.", "C’est l’approche clé en main de Pro Fer Forgé."]],
      ["Que faire maintenant", ["Prenez des photos de chaque structure, notez les zones où la rouille a percé ou où ça bouge, puis demandez une soumission. Nous vous disons ce qui relève de la peinture et ce qui exige de la soudure."]],
    ] },
    en: { title: "Repaint or restore your condo’s stairs: how to decide", tt: "Repaint or restore condo stairs: how to decide", desc: "Paint only, or weld first? The signs that tell you the right treatment for a condo’s wrought-iron stairs and balconies.", lead: "For a board of directors, the right question is not “how much to repaint?” but “what shape is the metal in?”. The answer decides everything else.", sections: [
      ["When paint is enough", ["The metal is sound: no holes, no thinned sections, no play in the joints.", "Paint is flaking, but rust is on the surface and can be ground out.", "In that case, thorough prep, an anti-rust primer and an industrial paint make the structure like new for many years."]],
      ["When welding comes first", ["Sections are perforated, badly thinned or deformed.", "A handrail, post or stringer moves.", "Rust has attacked the base of the railings or the support brackets.", "Painting over it solves nothing: replace or reinforce first, then paint."]],
      ["Why use one contractor for both", ["When welding and painting are done by the same crew, the prep is continuous, responsibility is clear and there is no coordination between two subcontractors.", "That is Pro Fer Forgé’s turnkey approach."]],
      ["What to do now", ["Photograph each structure, note where rust has gone through or where anything moves, then request a quote. We will tell you what is a painting job and what needs welding."]],
    ] },
  },
  g2: {
    fr: { title: "Préparer un projet de fer forgé pour votre copropriété ou coopérative", tt: "Préparer un projet de fer forgé en copropriété", desc: "Les informations à rassembler pour obtenir une soumission précise : photos, inventaire des structures, accès, échéancier.", lead: "Une bonne soumission commence par une bonne description. Voici ce qui fait gagner du temps à tout le monde.", sections: [
      ["1. Faites l’inventaire", ["Listez chaque structure : balcons, escaliers de service, escalier de façade, colimaçon, garde-corps, clôtures. Indiquez combien de chaque."]],
      ["2. Photographiez", ["Une vue d’ensemble et des gros plans des zones abîmées : base des poteaux, marches, jonctions, zones où l’eau stagne.", "Vous pouvez les joindre directement au formulaire de soumission (jusqu’à cinq photos)."]],
      ["3. Notez l’accès et les contraintes", ["Hauteur, cour arrière, stationnement, voisins proches, locataires à aviser. Cela aide à planifier un chantier propre."]],
      ["4. Précisez votre échéancier", ["Travaux avant l’hiver, avant une assemblée, avant une inspection ? Dites-le dès la demande."]],
      ["5. Tenez compte du minimum", ["Nous avons présentement un montant minimal de 3 000 $ par projet. Regrouper plusieurs structures dans une même soumission est souvent plus simple pour tout le monde."]],
    ] },
    en: { title: "Preparing a wrought-iron project for your condo or co-op", tt: "Prepare a wrought-iron project for your condo", desc: "What to gather for an accurate quote: photos, an inventory of structures, access and timeline.", lead: "A good quote starts with a good description. Here is what saves everyone time.", sections: [
      ["1. Take inventory", ["List each structure: balconies, service stairs, front stairs, spiral stairs, railings, fences. Note how many of each."]],
      ["2. Take photos", ["One overview and close-ups of damaged areas: post bases, treads, joints, places where water collects.", "You can attach them directly to the quote form (up to five photos)."]],
      ["3. Note access and constraints", ["Height, back yard, parking, close neighbours, tenants to notify. This helps plan a clean worksite."]],
      ["4. Give your timeline", ["Work before winter, before a meeting, before an inspection? Say so in your request."]],
      ["5. Keep the minimum in mind", ["We currently have a minimum of $3,000 per project. Grouping several structures in one quote is often simpler for everyone."]],
    ] },
  },
};

// Page copy
export const COPY = {
  fr: {
    home: {
      title: "Peinture et restauration de fer forgé à Montréal | Pro Fer Forgé",
      desc: "Pro Fer Forgé peint, soude et restaure escaliers, balcons et garde-corps en fer forgé à Montréal. Pour copropriétés et immeubles. Soumission gratuite.",
      eyebrow: "Pro Fer Forgé · Montréal",
      h1: "Peinture et restauration de fer forgé à Montréal",
      sub: "La référence des copropriétés pour l’entretien des escaliers, balcons et garde-corps. Soudure, préparation et peinture : un seul entrepreneur, un travail propre, une finition soignée.",
      intro: ["Un métal bien traité dure des décennies.", "Le climat de Montréal attaque le fer forgé : gel, dégel, humidité, sels. Nous arrêtons la rouille, renforçons ce qui est affaibli et protégeons le tout avec une finition industrielle. Clé en main, pour les moyens et gros projets d’entretien."],
      servicesH: "Deux métiers, un seul interlocuteur",
      svc: [
        { k: "paint", t: "Peinture de fer forgé", d: "Préparation minutieuse, primer antirouille et peinture industrielle pour protéger durablement balcons, escaliers et garde-corps." },
        { k: "weld", t: "Restauration et soudure", d: "Remplacement des sections dégradées, redressement et renforcement des zones amincies, avant la peinture." },
      ],
      structH: "Ce que nous restaurons",
      processH: "Notre processus de peinture, étape par étape",
      processSub: "Chaque étape protège la suivante. C’est la préparation qui décide de la durée du résultat.",
      whyH: "Pourquoi les copropriétés nous choisissent",
      why: [
        ["Service professionnel", "Une planification et une communication fluides, du premier appel à la fin du chantier."],
        ["Expertise locale", "Des méthodes et des produits conçus pour résister au climat d’ici."],
        ["Travail propre et durable", "Protection des lieux, finition soignée, résultat qui tient."],
        ["Clé en main", "Prise en charge complète du projet : soudure au besoin, préparation et peinture."],
      ],
      workH: "Voir la différence",
      workSub: "Du métal rouillé à une finition protégée. Glissez pour comparer.",
      reviewsH: "Ce que disent nos clients",
      areasH: "Montréal et sa région",
      areasSub: "Nous intervenons à Montréal et aux environs. Voici les secteurs desservis.",
      faqH: "Questions fréquentes",
      ctaH: "Un résultat propre, esthétique et durable.",
      ctaSub: "Demandez votre soumission gratuite. Quelques photos suffisent pour commencer.",
      note: "Montant minimal de 3 000 $ par projet.",
    },
    paint: {
      title: "Peinture de fer forgé à Montréal | Pro Fer Forgé",
      desc: "Peinture de fer forgé à Montréal : escaliers, balcons et garde-corps. Préparation, primer antirouille et peinture industrielle durable. Soumission gratuite.",
      h1: "Peinture de fer forgé à Montréal",
      lead: "Nous assurons la peinture et la protection durable de vos structures en fer forgé. Chaque projet débute par une préparation minutieuse : protection des surfaces, nettoyage, grattage, sablage et application d’une peinture industrielle résistante.",
      structH: "Types de structures en fer forgé",
      procH: "Notre processus",
      procBullets: ["Protection des surfaces avoisinantes", "Grattage et brossage de l’écaillement", "Meulage de la rouille et nettoyage", "Application de primer antirouille", "Application de peinture à métal industrielle"],
      durH: "Peinture durable et résistante",
      durP: "Nous utilisons des produits spécialisés pour les structures en acier et en fer forgé, conçus pour résister aux intempéries et assurer une protection durable. Selon l’état des surfaces et le budget, différentes options sont proposées.",
      crossP: "Si votre structure est endommagée, nous offrons aussi la",
      crossLink: "restauration et soudure de fer forgé à Montréal",
      ctaH: "Un résultat propre, esthétique et durable, protégé contre la corrosion.",
    },
    weld: {
      title: "Restauration et soudure de fer forgé à Montréal | Pro Fer Forgé",
      desc: "Restauration et soudure de fer forgé à Montréal : réparation d’escaliers, balcons et rampes. Remplacement, renforcement et consolidation. Soumission gratuite.",
      h1: "Restauration et soudure de fer forgé à Montréal",
      lead: "Un service complet pour vos structures en fer forgé, de la réparation à la finition. Les conditions climatiques du Québec accélèrent la détérioration du métal. Notre soudure remplace les sections trop dégradées et renforce les surfaces fragilisées.",
      cardsH: "Deux types d’intervention",
      cards: [
        ["Soudure de restauration", ["Remplacement de sections dégradées", "Redressement de structures"]],
        ["Soudure préventive", ["Consolidation de sections affaiblies", "Renforcement de zones amincies"]],
      ],
      structH: "Interventions courantes",
      crossP: "Après réparation, nous offrons également la",
      crossLink: "peinture de fer forgé à Montréal",
      crossEnd: "pour protéger et uniformiser les surfaces.",
      ctaH: "Une structure solide, sécuritaire et durable.",
    },
    work: {
      title: "Réalisations de fer forgé à Montréal | Pro Fer Forgé",
      desc: "Avant et après : peinture et restauration de fer forgé à Montréal. Comparez l’état du métal avant et après le travail de Pro Fer Forgé.",
      h1: "Nos réalisations",
      lead: "Du métal écaillé et rouillé à une finition protégée. Comparez l’avant et l’après.",
      note: "Les images de cette page sont des illustrations en attendant les photos de chantiers.",
      demoH: "Garde-corps : avant et après",
      steps: ["Rouille et peinture écaillée", "Préparation et primer", "Peinture industrielle"],
      ctaH: "Votre structure est la prochaine ?",
    },
    about: {
      title: "À propos de Pro Fer Forgé | Fer forgé à Montréal",
      desc: "Pro Fer Forgé est spécialisé en peinture, restauration et soudure de fer forgé à Montréal. Service professionnel et durable pour copropriétés et immeubles.",
      h1: "À propos de Pro Fer Forgé",
      h2: "Votre spécialiste du fer forgé à Montréal",
      p: [
        "Pro Fer Forgé est spécialisé en peinture, restauration et soudure de fer forgé à Montréal et aux environs. Depuis plusieurs années, nous accompagnons copropriétés, coopératives et propriétaires d’immeubles dans l’entretien et la remise en état de leurs structures, en assurant sécurité, conformité et durabilité.",
        "Nous intervenons sur les balcons, escaliers, rampes et autres structures métalliques grâce à un service complet de peinture de fer forgé à Montréal et de restauration et soudure de fer forgé.",
        "Travail propre, méthodes professionnelles et résultats durables.",
      ],
      methodH: "Notre méthode",
      method: ["Inspection et diagnostic de vos installations", "Préparation adaptée à chaque structure", "Réalisation de travaux soignés, soudure et peinture incluses", "Protection durable contre la corrosion"],
      commitH: "Nos engagements",
      commit: ["Travail soigné et durable", "Respect des délais", "Satisfaction client"],
      ctaH: "Un service fiable pour vos structures en fer forgé",
    },
    areas: {
      title: "Zones desservies : fer forgé à Montréal et environs | Pro Fer Forgé",
      desc: "Pro Fer Forgé intervient à Montréal et dans toute la région : Plateau, Rosemont, Verdun, Laval, Longueuil et plus. Peinture et soudure de fer forgé.",
      h1: "Basés à Montréal, nous desservons toute la région",
      lead: "Notre adresse est sur l’avenue du Mont-Royal Est. Nous nous déplaçons chez vous pour la soumission et pour le chantier.",
      listH: "Secteurs desservis",
      whyH: "Un parc d’escaliers extérieurs unique",
      whyP: "À Montréal, de nombreux immeubles ont des escaliers, balcons et garde-corps en fer forgé exposés aux saisons. Les entretenir à temps évite des réparations lourdes.",
      mapBtn: "Ouvrir dans Google Maps",
      ctaH: "Vous êtes dans le secteur ? Demandez votre soumission.",
    },
    faq: { title: "Questions fréquentes sur le fer forgé à Montréal | Pro Fer Forgé", desc: "Réponses aux questions fréquentes : types de structures, soudure, processus de peinture, montant minimal et soumission gratuite.", h1: "Questions fréquentes", lead: "Réponses rapides avant de demander une soumission.", ctaH: "Une autre question ?" },
    guides: { title: "Guides pour copropriétés : fer forgé | Pro Fer Forgé", desc: "Guides pratiques pour conseils d’administration de copropriété : repeindre ou restaurer, préparer un projet de fer forgé.", h1: "Guides pour copropriétés et immeubles", lead: "Des conseils concrets pour décider et préparer vos travaux." },
    contact: {
      title: "Soumission gratuite fer forgé Montréal | Pro Fer Forgé",
      desc: "Obtenez une soumission gratuite pour vos travaux de peinture, restauration et soudure de fer forgé à Montréal. Joignez vos photos. Réponse rapide.",
      h1: "Obtenez une soumission gratuite",
      lead: "Décrivez votre projet et joignez quelques photos. Plus nous en savons, plus la soumission est précise.",
      min: "Veuillez noter que nous avons présentement un montant minimal de {min} par projet.",
      thanks: "Au plaisir de travailler avec vous !",
      f: { name: "Nom complet", phone: "Téléphone", email: "Courriel", postal: "Code postal", address: "Adresse des travaux", clientType: "Vous êtes", ct: ["Copropriété", "Coopérative d’habitation", "Propriétaire d’immeuble", "Autre"], work: "Type de travaux", wk: ["Peinture", "Soudure / restauration", "Les deux", "Je ne sais pas"], struct: "Structures concernées", timeline: "Échéancier souhaité", tl: ["Dès que possible", "Dans 1 à 3 mois", "Cette saison", "Je planifie"], msg: "Description du projet", photos: "Photos (jusqu’à 5)", photosHelp: "JPG ou PNG, 8 Mo maximum chacune.", consent: "J’accepte que Pro Fer Forgé utilise ces renseignements pour répondre à ma demande, conformément à la <a href=\"{priv}\">politique de confidentialité</a>.", optional: "facultatif" },
      alt: "Vous préférez parler à quelqu’un ?",
    },
    privacy: { title: "Politique de confidentialité | Pro Fer Forgé", desc: "Comment Pro Fer Forgé recueille, utilise et protège vos renseignements personnels, conformément à la Loi 25 du Québec.", h1: "Politique de confidentialité" },
    notFound: { title: "Page introuvable | Pro Fer Forgé", h1: "Cette page est introuvable", p: "Elle a peut-être été déplacée. Retournez à l’accueil ou demandez une soumission." },
    ctaFoot: "Obtenez une soumission gratuite",
    homeSchemaDesc: "Peinture, restauration et soudure de fer forgé à Montréal : escaliers, balcons et garde-corps, pour copropriétés, coopératives et immeubles.",
  },
  en: {
    home: {
      title: "Wrought iron painting & restoration in Montréal | Pro Fer Forgé",
      desc: "Pro Fer Forgé paints, welds and restores wrought-iron stairs, balconies and railings in Montréal. For condos and buildings. Free quote.",
      eyebrow: "Pro Fer Forgé · Montréal",
      h1: "Wrought iron painting and restoration in Montréal",
      sub: "The go-to contractor for condo associations’ stairs, balconies and railings. Welding, prep and paint: one contractor, clean work, a careful finish.",
      intro: ["Well-treated metal lasts for decades.", "Montréal’s climate attacks wrought iron: freeze, thaw, moisture, salt. We stop the rust, reinforce what is weakened and protect it all with an industrial finish. Turnkey, for medium and large maintenance projects."],
      servicesH: "Two trades, one contractor",
      svc: [
        { k: "paint", t: "Wrought iron painting", d: "Careful prep, anti-rust primer and industrial paint to durably protect balconies, stairs and railings." },
        { k: "weld", t: "Restoration and welding", d: "Replacement of degraded sections, straightening and reinforcement of thinned areas, ahead of painting." },
      ],
      structH: "What we restore",
      processH: "Our painting process, step by step",
      processSub: "Each step protects the next. Preparation decides how long the result lasts.",
      whyH: "Why condo boards choose us",
      why: [
        ["Professional service", "Smooth planning and communication, from the first call to the end of the job."],
        ["Local expertise", "Methods and products designed to withstand our climate."],
        ["Clean, durable work", "Surfaces protected, a careful finish, a result that lasts."],
        ["Turnkey", "Complete project handling: welding where needed, prep and paint."],
      ],
      workH: "See the difference",
      workSub: "From rusted metal to a protected finish. Drag to compare.",
      reviewsH: "What our clients say",
      areasH: "Montréal and its region",
      areasSub: "We work in Montréal and the surrounding area. These are the sectors we serve.",
      faqH: "Frequently asked questions",
      ctaH: "A clean, attractive and lasting result.",
      ctaSub: "Request your free quote. A few photos are enough to start.",
      note: "Minimum project amount of $3,000.",
    },
    paint: {
      title: "Wrought iron painting in Montréal | Pro Fer Forgé",
      desc: "Wrought iron painting in Montréal: stairs, balconies and railings. Prep, anti-rust primer and durable industrial paint. Free quote.",
      h1: "Wrought iron painting in Montréal",
      lead: "We paint and durably protect your wrought-iron structures. Every project starts with careful preparation: surface protection, cleaning, scraping, sanding and a tough industrial paint.",
      structH: "Types of wrought-iron structures",
      procH: "Our process",
      procBullets: ["Protecting surrounding surfaces", "Scraping and brushing flaking paint", "Grinding rust and cleaning", "Applying anti-rust primer", "Applying industrial metal paint"],
      durH: "Durable, resistant paint",
      durP: "We use specialist products for steel and wrought-iron structures, built to withstand the weather and protect for the long term. Depending on the condition of the surfaces and the budget, different options are offered.",
      crossP: "If your structure is damaged, we also offer",
      crossLink: "wrought iron restoration and welding in Montréal",
      ctaH: "A clean, attractive and lasting result, protected against corrosion.",
    },
    weld: {
      title: "Wrought iron restoration & welding in Montréal | Pro Fer Forgé",
      desc: "Wrought iron restoration and welding in Montréal: repair of stairs, balconies and railings. Replacement, reinforcement and consolidation. Free quote.",
      h1: "Wrought iron restoration and welding in Montréal",
      lead: "A complete service for your wrought-iron structures, from repair to finish. Québec’s weather speeds up the deterioration of metal. Our welding replaces sections that are too far gone and reinforces weakened surfaces.",
      cardsH: "Two types of intervention",
      cards: [
        ["Restoration welding", ["Replacement of degraded sections", "Straightening of structures"]],
        ["Preventive welding", ["Consolidation of weakened sections", "Reinforcement of thinned areas"]],
      ],
      structH: "Common interventions",
      crossP: "After repair, we also offer",
      crossLink: "wrought iron painting in Montréal",
      crossEnd: "to protect and even out the surfaces.",
      ctaH: "A solid, safe and lasting structure.",
    },
    work: {
      title: "Wrought iron projects in Montréal | Pro Fer Forgé",
      desc: "Before and after: wrought iron painting and restoration in Montréal. Compare the metal before and after Pro Fer Forgé’s work.",
      h1: "Our projects",
      lead: "From flaking, rusted metal to a protected finish. Compare before and after.",
      note: "Images on this page are illustrations until site photos are added.",
      demoH: "Railing: before and after",
      steps: ["Rust and flaking paint", "Prep and primer", "Industrial paint"],
      ctaH: "Is your structure next?",
    },
    about: {
      title: "About Pro Fer Forgé | Wrought iron in Montréal",
      desc: "Pro Fer Forgé specializes in wrought iron painting, restoration and welding in Montréal. Professional, durable service for condos and buildings.",
      h1: "About Pro Fer Forgé",
      h2: "Your wrought-iron specialist in Montréal",
      p: [
        "Pro Fer Forgé specializes in wrought iron painting, restoration and welding in Montréal and the surrounding area. For several years we have supported condo associations, co-ops and building owners in maintaining and restoring their structures, ensuring safety, compliance and durability.",
        "We work on balconies, stairs, railings and other metal structures through a complete service of wrought iron painting and wrought iron restoration and welding in Montréal.",
        "Clean work, professional methods and lasting results.",
      ],
      methodH: "Our method",
      method: ["Inspection and diagnosis of your installations", "Preparation adapted to each structure", "Careful work, welding and painting included", "Lasting protection against corrosion"],
      commitH: "Our commitments",
      commit: ["Careful, durable work", "Deadlines respected", "Client satisfaction"],
      ctaH: "A reliable service for your wrought-iron structures",
    },
    areas: {
      title: "Service area: wrought iron in Montréal and region | Pro Fer Forgé",
      desc: "Pro Fer Forgé works in Montréal and the whole region: Plateau, Rosemont, Verdun, Laval, Longueuil and more. Wrought iron painting and welding.",
      h1: "Based in Montréal, serving the whole region",
      lead: "We are located on Mont-Royal Avenue East. We come to you for the quote and for the job.",
      listH: "Areas we serve",
      whyH: "A unique stock of outdoor stairs",
      whyP: "In Montréal, many buildings have wrought-iron stairs, balconies and railings exposed to the seasons. Maintaining them in time avoids heavy repairs.",
      mapBtn: "Open in Google Maps",
      ctaH: "In our area? Request your quote.",
    },
    faq: { title: "Wrought iron FAQ, Montréal | Pro Fer Forgé", desc: "Answers to common questions: structure types, welding, the painting process, minimum amount and free quote.", h1: "Frequently asked questions", lead: "Quick answers before you request a quote.", ctaH: "Another question?" },
    guides: { title: "Guides for condo associations: wrought iron | Pro Fer Forgé", desc: "Practical guides for condo boards: repaint or restore, how to prepare a wrought-iron project.", h1: "Guides for condos and buildings", lead: "Practical advice for deciding and preparing your work." },
    contact: {
      title: "Free wrought iron quote, Montréal | Pro Fer Forgé",
      desc: "Get a free quote for wrought iron painting, restoration and welding in Montréal. Attach your photos. Fast reply.",
      h1: "Get a free quote",
      lead: "Describe your project and attach a few photos. The more we know, the more precise the quote.",
      min: "Please note that we currently have a minimum of {min} per project.",
      thanks: "Looking forward to working with you!",
      f: { name: "Full name", phone: "Phone", email: "Email", postal: "Postal code", address: "Job address", clientType: "You are", ct: ["Condo association", "Housing co-op", "Building owner", "Other"], work: "Type of work", wk: ["Painting", "Welding / restoration", "Both", "Not sure"], struct: "Structures involved", timeline: "Preferred timeline", tl: ["As soon as possible", "In 1 to 3 months", "This season", "I am planning"], msg: "Project description", photos: "Photos (up to 5)", photosHelp: "JPG or PNG, 8 MB maximum each.", consent: "I agree that Pro Fer Forgé may use this information to answer my request, in line with the <a href=\"{priv}\">privacy policy</a>.", optional: "optional" },
      alt: "Prefer to talk to someone?",
    },
    privacy: { title: "Privacy policy | Pro Fer Forgé", desc: "How Pro Fer Forgé collects, uses and protects your personal information, in line with Québec’s Law 25.", h1: "Privacy policy" },
    notFound: { title: "Page not found | Pro Fer Forgé", h1: "This page could not be found", p: "It may have moved. Go back home or request a quote." },
    ctaFoot: "Get a free quote",
    homeSchemaDesc: "Wrought iron painting, restoration and welding in Montréal: stairs, balconies and railings, for condo associations, co-ops and buildings.",
  },
};

export const PRIVACY = {
  fr: [
    ["Qui sommes-nous", "Pro Fer Forgé exploite le site proferforge.ca. La personne responsable de la protection des renseignements personnels peut être jointe à l’adresse indiquée en bas de cette page."],
    ["Renseignements recueillis", "Par le formulaire de soumission : nom, téléphone, courriel, code postal, adresse des travaux, description du projet et photos que vous choisissez de joindre. Avec votre accord seulement : statistiques de visite anonymisées par témoins de mesure d’audience."],
    ["Pourquoi", "Répondre à votre demande de soumission, planifier les travaux et améliorer le site. Nous n’utilisons pas vos renseignements à d’autres fins sans votre consentement."],
    ["Témoins (cookies)", "Aucun témoin de mesure n’est déposé avant que vous les acceptiez dans le bandeau. Vous pouvez refuser, et changer d’avis en tout temps depuis le lien « Gérer les témoins » au bas des pages."],
    ["Communication à des tiers", "Nous ne vendons pas vos renseignements. Ils peuvent transiter par nos fournisseurs techniques (hébergement du site, service de courriel, outil de mesure d’audience si accepté) uniquement pour fournir le service."],
    ["Conservation", "Les demandes de soumission sont conservées le temps nécessaire pour répondre et assurer le suivi du projet, puis détruites ou anonymisées lorsqu’elles ne sont plus utiles."],
    ["Vos droits", "Vous pouvez demander l’accès, la rectification ou la suppression de vos renseignements, ou retirer votre consentement, en nous écrivant. Nous répondons dans les délais prévus par la Loi 25."],
    ["Incident de confidentialité", "En cas d’incident présentant un risque de préjudice sérieux, nous avisons les personnes concernées et la Commission d’accès à l’information du Québec."],
  ],
  en: [
    ["Who we are", "Pro Fer Forgé operates the website proferforge.ca. The person in charge of personal-information protection can be reached at the address at the bottom of this page."],
    ["Information we collect", "Through the quote form: name, phone, email, postal code, job address, project description and any photos you choose to attach. With your consent only: anonymised visit statistics through audience-measurement cookies."],
    ["Why", "To answer your quote request, plan the work and improve the site. We do not use your information for other purposes without your consent."],
    ["Cookies", "No measurement cookie is set until you accept it in the banner. You can decline, and change your mind at any time from the “Manage cookies” link at the bottom of the pages."],
    ["Sharing with third parties", "We do not sell your information. It may pass through our technical providers (site hosting, email service, audience-measurement tool if accepted) only to provide the service."],
    ["Retention", "Quote requests are kept as long as needed to reply and follow the project, then destroyed or anonymised when no longer useful."],
    ["Your rights", "You can request access to, correction or deletion of your information, or withdraw your consent, by writing to us. We reply within the time limits set by Law 25."],
    ["Privacy incidents", "If an incident presents a risk of serious harm, we notify the people concerned and Québec’s Commission d’accès à l’information."],
  ],
};
