// Builds every menu output from data/menu.source.json (the single source of truth).
//   node tools/build-menu.mjs
// Outputs: data/menu.json (enriched, used by the website, QR menu and screens),
//          data/menu.csv (for POS / delivery-platform imports),
//          docs/generated/menu-engineering.md (Stars / Plowhorses / Puzzles / Dogs).
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = JSON.parse(readFileSync(join(root, "data/menu.source.json"), "utf8"));

const ALLERGENS = {
  gluten: { fr: "Gluten (blé, avoine, orge)", en: "Gluten (wheat, oats, barley)", icon: "G" },
  milk: { fr: "Lait", en: "Milk", icon: "L" },
  eggs: { fr: "Œufs", en: "Eggs", icon: "Œ" },
  tree_nuts: { fr: "Noix", en: "Tree nuts", icon: "N" },
  peanuts: { fr: "Arachides", en: "Peanuts", icon: "A" },
  sesame: { fr: "Sésame", en: "Sesame", icon: "S" },
  soy: { fr: "Soya", en: "Soy", icon: "So" },
  fish: { fr: "Poisson", en: "Fish", icon: "P" },
  shellfish: { fr: "Crustacés et mollusques", en: "Crustaceans & shellfish", icon: "C" },
  mustard: { fr: "Moutarde", en: "Mustard", icon: "M" },
  sulphites: { fr: "Sulfites", en: "Sulphites", icon: "Su" },
};
const TAGS = {
  vegan: { fr: "Végane", en: "Vegan" },
  vegetarian: { fr: "Végé", en: "Vegetarian" },
  halal: { fr: "Halal", en: "Halal" },
  signature: { fr: "Signature", en: "Signature" },
  spicy_mild: { fr: "Relevé", en: "A little heat" },
  no_gluten_ingredients: { fr: "Sans ingrédient à gluten", en: "No gluten ingredients" },
};

// Delivery price: +15 % markup to offset commissions, rounded up to the next 0.25.
const deliveryPrice = (p) => Math.ceil(p * (1 + src.meta.delivery_markup) * 4) / 4;
const r2 = (n) => Math.round(n * 100) / 100;

const items = src.items.map((it) => {
  const catering = it.cat === "traiteur";
  const channels = {
    dine_in: !catering,
    takeout: !catering && !src.takeout_exclude.includes(it.id),
    online_pickup: !catering && !src.takeout_exclude.includes(it.id),
    delivery: !src.delivery_exclude.includes(it.id),
    catering: catering || ["bol_mezze", "bol_poulet", "pita_poulet", "wrap_falafel", "cookie_tahini", "limonade"].includes(it.id),
    screens: !catering && !it.tags.includes("modifier"),
  };
  return {
    ...it,
    price_delivery: channels.delivery ? deliveryPrice(it.price) : null,
    food_cost_pct: r2((it.cost / it.price) * 100),
    contribution_margin: r2(it.price - it.cost),
    photo: `${it.id}.jpg`,
    channels,
  };
});

const out = { meta: src.meta, dayparts: src.dayparts, categories: src.categories, allergens: ALLERGENS, tags: TAGS, items };
writeFileSync(join(root, "data/menu.json"), JSON.stringify(out, null, 2) + "\n");

// CSV
const esc = (v) => {
  const s = v == null ? "" : String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
const cols = ["id", "cat", "fr", "en", "desc_fr", "desc_en", "price", "price_delivery", "cost", "food_cost_pct", "contribution_margin", "allergens", "tags", "dayparts", "photo", "dine_in", "takeout", "online_pickup", "delivery", "catering", "screens"];
const rows = items.map((it) =>
  cols.map((c) => {
    if (c in it.channels) return it.channels[c] ? "yes" : "no";
    const v = it[c];
    return esc(Array.isArray(v) ? v.join("|") : v);
  }).join(",")
);
writeFileSync(join(root, "data/menu.csv"), [cols.join(","), ...rows].join("\n") + "\n");

// Menu engineering (Kasavana & Smith): analysed within comparable groups.
const groups = { boissons: "Drinks", douceurs: "Pastries & sweets", plats: "Brunch & lunch mains", soir: "Mezze evenings" };
const catGroup = Object.fromEntries(src.categories.map((c) => [c.id, c.group]));
const ACTIONS = {
  Star: "Keep. Protect recipe and portion; top-right of section, photo, signature badge. Test +0.50 to +1.00.",
  Plowhorse: "Popular but low margin: re-cost recipe/portion, bundle with high-margin add-on, small price increase, move to a less prominent slot.",
  Puzzle: "Profitable but under-ordered: rename/redescribe, add photo or badge, move to golden-triangle slot, train staff to recommend, feature on screens.",
  Dog: "Low on both: remove, replace, or keep only if it serves a strategic role (dietary need, kids, signature story).",
};
let md = `# Menu engineering matrix (generated)\n\n> Generated by \`tools/build-menu.mjs\` from \`data/menu.source.json\` on ${src.meta.version}.\n> **Units are projected weekly sales (pre-opening assumption).** Re-run with 8 weeks of real POS data and the classification will update automatically.\n\nMethod: within each group, **popularity** is high when an item's mix share ≥ 70 % × (1 ÷ number of items); **profitability** is high when its contribution margin (price − food cost) ≥ the group's weighted-average margin. Modifiers, combos, kids and catering are excluded, because they are priced to support other items.\n\n`;
const summary = [];
for (const [g, label] of Object.entries(groups)) {
  const gi = items.filter((it) => catGroup[it.cat] === g && !it.tags.includes("modifier") && !it.tags.includes("combo"));
  const totalUnits = gi.reduce((s, it) => s + it.units, 0);
  const totalCM = gi.reduce((s, it) => s + it.units * it.contribution_margin, 0);
  const avgCM = totalCM / totalUnits;
  const popThreshold = 0.7 * (1 / gi.length);
  md += `## ${label}\n\nItems: ${gi.length} · Weekly units: ${totalUnits} · Weighted avg. margin: $${avgCM.toFixed(2)} · Popularity threshold: ${(popThreshold * 100).toFixed(1)} % of mix\n\n| Item | Price | Food cost | FC % | Margin | Units/wk | Mix % | Class | Action |\n|---|---:|---:|---:|---:|---:|---:|---|---|\n`;
  for (const it of gi.sort((a, b) => b.units * b.contribution_margin - a.units * a.contribution_margin)) {
    const mix = it.units / totalUnits;
    const pop = mix >= popThreshold;
    const prof = it.contribution_margin >= avgCM;
    const cls = pop && prof ? "Star" : pop ? "Plowhorse" : prof ? "Puzzle" : "Dog";
    summary.push({ id: it.id, name: it.fr, group: label, cls });
    md += `| ${it.fr} | ${it.price.toFixed(2)} | ${it.cost.toFixed(2)} | ${it.food_cost_pct.toFixed(1)} | ${it.contribution_margin.toFixed(2)} | ${it.units} | ${(mix * 100).toFixed(1)} | **${cls}** | ${ACTIONS[cls].split(":")[0].split(".")[0]} |\n`;
  }
  md += "\n";
}
const totalRev = items.reduce((s, it) => s + it.price * it.units, 0);
const totalCost = items.reduce((s, it) => s + it.cost * it.units, 0);
md += `## Whole-menu projection\n\nProjected weekly food & beverage revenue (menu prices, all channels at dine-in price): **$${totalRev.toFixed(0)}** · Theoretical food cost: **${((totalCost / totalRev) * 100).toFixed(1)} %** (target 26–30 % before waste; actual will run 2–4 points higher).\n\n## Action key\n\n`;
for (const [k, v] of Object.entries(ACTIONS)) md += `- **${k}**: ${v}\n`;
mkdirSync(join(root, "docs/generated"), { recursive: true });
writeFileSync(join(root, "docs/generated/menu-engineering.md"), md);
writeFileSync(join(root, "docs/generated/menu-engineering.json"), JSON.stringify(summary, null, 2) + "\n");
// Print-menu copy for the designer: FR first, EN below, allergen letters, no currency symbol.
const fmt = (p) => (Number.isInteger(p) ? String(p) : p.toFixed(2).replace(/0$/, "").replace(".", ","));
let pm = `# Print menu copy (generated)\n\n> Generated from \`data/menu.source.json\`. Paste into the layout as-is. Prices shown without "$", following Phase 3 §2. French is the primary text (larger); English sits below it in italic at 85 % size.\n\n`;
for (const cat of src.categories.filter((c) => c.id !== "traiteur")) {
  const ci = items.filter((it) => it.cat === cat.id);
  if (!ci.length) continue;
  pm += `## ${cat.fr.toUpperCase()} / *${cat.en}*\n`;
  if (cat.note_fr) pm += `_${cat.note_fr} · ${cat.note_en}_\n`;
  pm += "\n";
  for (const it of ci) {
    const badges = [it.tags.includes("signature") ? "★ SIGNATURE" : "", it.tags.includes("vegan") ? "VÉGANE" : it.tags.includes("vegetarian") ? "VÉGÉ" : "", it.tags.includes("halal") ? "HALAL" : "", it.tags.includes("spicy_mild") ? "🌶" : ""].filter(Boolean).join(" · ");
    const al = it.allergens.map((a) => ALLERGENS[a].icon).join(" ");
    pm += `**${it.fr}** ${fmt(it.price)}${badges ? `  \`${badges}\`` : ""}  \n*${it.en}*  \n`;
    if (it.desc_fr) pm += `${it.desc_fr}  \n*${it.desc_en}*  \n`;
    if (al) pm += `Allergènes / Allergens: ${al}\n`;
    pm += "\n";
  }
}
pm += `---\n**Légende des allergènes / Allergen key:** ${Object.values(ALLERGENS).map((a) => `${a.icon} = ${a.fr} / ${a.en}`).join(" · ")}\n\n${src.meta.allergen_note_fr}  \n*${src.meta.allergen_note_en}*\n\n${src.meta.tax_note_fr} *${src.meta.tax_note_en}*\n`;
writeFileSync(join(root, "docs/generated/print-menu.md"), pm);

console.log(`menu.json: ${items.length} items · weekly rev $${totalRev.toFixed(0)} · FC ${((totalCost / totalRev) * 100).toFixed(1)}%`);
